spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.auuadvpflzvxuteljpmu
spring.datasource.password=Anton0567809901

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.auto-commit=false

spring.datasource.hikari.connection-test-query=SELECT 1

spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.statement_cache.size=0
